theme: jekyll-theme-cayman

title: [Dr Arkaprabha Sau]
description: [MBBS MD (Gold Medalist) DPH Dip Geriatric Medicine PhD (Research Scholar in Health Informatics)]

# User settings
username: arka1985
user_description: Dr Arkaprabha Sau
user_title: Dr Arkaprabha Sau
email: arka.doctor@gmail.com
twitter_username: Arka14695653
github_username:  arka1985
