theme: jekyll-theme-cayman

title: [The title of your site]
description: [A short description of your site's purpose]

# User settings
username: arka1985
user_description: Dr Arkaprabha Sau
user_title: Dr Arkaprabha Sau
email: arka.doctor@gmail.com
twitter_username: Arka14695653
github_username:  arka1985
